// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiAuthTestHelloTeacherData, GetApiAuthTestHelloTeacherResponses, PostApiAuthLoginData, PostApiAuthLoginResponses, PostApiAuthRefreshTokenData, PostApiAuthRefreshTokenResponses, PostApiAuthRegisterData, PostApiAuthRegisterResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postApiAuthLogin = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthLoginData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiAuthLoginResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/Auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const postApiAuthRefreshToken = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthRefreshTokenData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiAuthRefreshTokenResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/Auth/refreshToken',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getApiAuthTestHelloTeacher = <ThrowOnError extends boolean = false>(options?: Options<GetApiAuthTestHelloTeacherData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiAuthTestHelloTeacherResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/Auth/test-hello-teacher',
        ...options
    });
};

export const postApiAuthRegister = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthRegisterData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiAuthRegisterResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/Auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};
