// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5000' | (string & {});
};

export type RefreshTokenRequestPayload = {
    refreshToken?: string | null;
};

export type UserAuthRequestPayload = {
    login: string;
    password: string;
};

export type UserRegisterRequestPayload = {
    name: string;
    surname: string;
    dateOfBirth: string;
    login: string;
    password: string;
};

export type PostApiAuthLoginData = {
    body?: UserAuthRequestPayload;
    path?: never;
    query?: never;
    url: '/api/Auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthRefreshTokenData = {
    body?: RefreshTokenRequestPayload;
    path?: never;
    query?: never;
    url: '/api/Auth/refreshToken';
};

export type PostApiAuthRefreshTokenResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiAuthTestHelloTeacherData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/test-hello-teacher';
};

export type GetApiAuthTestHelloTeacherResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthRegisterData = {
    body?: UserRegisterRequestPayload;
    path?: never;
    query?: never;
    url: '/api/Auth/register';
};

export type PostApiAuthRegisterResponses = {
    /**
     * Success
     */
    200: unknown;
};
